[2023-11-24T20:15:21.658+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Projet1.Extract manual__2023-11-24T20:14:31.816164+00:00 [queued]>
[2023-11-24T20:15:21.677+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Projet1.Extract manual__2023-11-24T20:14:31.816164+00:00 [queued]>
[2023-11-24T20:15:21.678+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-24T20:15:21.724+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Extract> on 2023-11-24 20:14:31.816164+00:00
[2023-11-24T20:15:21.836+0000] {standard_task_runner.py:57} INFO - Started process 4136 to run task
[2023-11-24T20:15:21.858+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Projet1', 'Extract', 'manual__2023-11-24T20:14:31.816164+00:00', '--job-id', '1113', '--raw', '--subdir', 'DAGS_FOLDER/Projet.py', '--cfg-path', '/tmp/tmpywg55r8w']
[2023-11-24T20:15:21.861+0000] {standard_task_runner.py:85} INFO - Job 1113: Subtask Extract
[2023-11-24T20:15:22.178+0000] {task_command.py:416} INFO - Running <TaskInstance: Projet1.Extract manual__2023-11-24T20:14:31.816164+00:00 [running]> on host b36ebcee5948
[2023-11-24T20:15:22.270+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='filali.dia18@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Projet1' AIRFLOW_CTX_TASK_ID='Extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-24T20:14:31.816164+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-24T20:14:31.816164+00:00'
[2023-11-24T20:15:22.498+0000] {warnings.py:109} WARNING - /opt/***/dags/Projet.py:44: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_urgences = pd.read_csv(csv_file_path_urgences, delimiter=';')

[2023-11-24T20:15:22.773+0000] {logging_mixin.py:151} INFO - Index(['code_age', 'agess'], dtype='object')
[2023-11-24T20:15:22.783+0000] {base.py:73} INFO - Using connection ID 'postgres_connexion' for task execution.
[2023-11-24T20:15:22.822+0000] {logging_mixin.py:151} INFO - Une erreur s'est produite : (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "Departements_pkey"
DETAIL:  Key (num_dep)=(01) already exists.

[SQL: INSERT INTO "Departements" (num_dep, dep_name, region_name) VALUES (%(num_dep)s, %(dep_name)s, %(region_name)s)]
[parameters: ({'num_dep': '01', 'dep_name': 'Ain', 'region_name': 'Auvergne-Rhône-Alpes'}, {'num_dep': '02', 'dep_name': 'Aisne', 'region_name': 'Hauts-de-France'}, {'num_dep': '03', 'dep_name': 'Allier', 'region_name': 'Auvergne-Rhône-Alpes'}, {'num_dep': '04', 'dep_name': 'Alpes-de-Haute-Provence', 'region_name': "Provence-Alpes-Côte d'Azur"}, {'num_dep': '05', 'dep_name': 'Hautes-Alpes', 'region_name': "Provence-Alpes-Côte d'Azur"}, {'num_dep': '06', 'dep_name': 'Alpes-Maritimes', 'region_name': "Provence-Alpes-Côte d'Azur"}, {'num_dep': '07', 'dep_name': 'Ardèche', 'region_name': 'Auvergne-Rhône-Alpes'}, {'num_dep': '08', 'dep_name': 'Ardennes', 'region_name': 'Grand Est'}  ... displaying 10 of 102 total bound parameter sets ...  {'num_dep': '0', 'dep_name': 'tunisie', 'region_name': 'La Réunion'}, {'num_dep': '976', 'dep_name': 'Mayotte', 'region_name': 'Mayotte'})]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2023-11-24T20:15:22.823+0000] {logging_mixin.py:151} INFO - ########################################################################
[2023-11-24T20:15:22.823+0000] {logging_mixin.py:151} INFO - #                                                                      #
[2023-11-24T20:15:22.824+0000] {logging_mixin.py:151} INFO - #   ce dessous est la visualisation du contenu de la table Urgences :  #
[2023-11-24T20:15:22.825+0000] {logging_mixin.py:151} INFO - #                                                                      #
[2023-11-24T20:15:22.826+0000] {logging_mixin.py:151} INFO - ########################################################################
[2023-11-24T20:15:22.827+0000] {logging_mixin.py:151} INFO - ========================
[2023-11-24T20:15:23.244+0000] {base.py:73} INFO - Using connection ID 'postgres_connexion' for task execution.
[2023-11-24T20:15:23.256+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return psql.read_sql(sql, con=conn, params=parameters, **kwargs)

[2023-11-24T20:15:23.804+0000] {base.py:73} INFO - Using connection ID 'postgres_connexion' for task execution.
[2023-11-24T20:15:24.260+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-24T20:15:24.271+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Projet1, task_id=Extract, execution_date=20231124T201431, start_date=20231124T201521, end_date=20231124T201524
[2023-11-24T20:15:24.296+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-24T20:15:24.320+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
