[2023-11-11T21:50:24.332+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: A.Extract manual__2023-11-11T21:50:22.166662+00:00 [queued]>
[2023-11-11T21:50:24.341+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: A.Extract manual__2023-11-11T21:50:22.166662+00:00 [queued]>
[2023-11-11T21:50:24.342+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-11T21:50:24.356+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): Extract> on 2023-11-11 21:50:22.166662+00:00
[2023-11-11T21:50:24.362+0000] {standard_task_runner.py:57} INFO - Started process 27057 to run task
[2023-11-11T21:50:24.365+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'A', 'Extract', 'manual__2023-11-11T21:50:22.166662+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/Projet.py', '--cfg-path', '/tmp/tmpn1yc_uzs']
[2023-11-11T21:50:24.367+0000] {standard_task_runner.py:85} INFO - Job 88: Subtask Extract
[2023-11-11T21:50:24.417+0000] {task_command.py:416} INFO - Running <TaskInstance: A.Extract manual__2023-11-11T21:50:22.166662+00:00 [running]> on host fb26c01043df
[2023-11-11T21:50:24.500+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='A' AIRFLOW_CTX_TASK_ID='Extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-11T21:50:22.166662+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-11T21:50:22.166662+00:00'
[2023-11-11T21:50:24.507+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-11T21:50:24.510+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl --keepalive-time 6000 -o ${AIRFLOW_HOME}/data/valeurs.csv file:///TP_Airflow/data/code-tranches-dage-donnees-urgences.csv']
[2023-11-11T21:50:24.542+0000] {subprocess.py:86} INFO - Output:
[2023-11-11T21:50:24.567+0000] {subprocess.py:93} INFO - curl: (37) Couldn't open file /TP_Airflow/data/code-tranches-dage-donnees-urgences.csv
[2023-11-11T21:50:24.569+0000] {subprocess.py:97} INFO - Command exited with return code 37
[2023-11-11T21:50:24.580+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 37.
[2023-11-11T21:50:24.585+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=A, task_id=Extract, execution_date=20231111T215022, start_date=20231111T215024, end_date=20231111T215024
[2023-11-11T21:50:24.612+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 88 for task Extract (Bash command failed. The command returned a non-zero exit code 37.; 27057)
[2023-11-11T21:50:24.660+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-11T21:50:24.883+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
