[2023-11-15T16:52:12.751+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Projet1.Extract manual__2023-11-15T16:52:10.553396+00:00 [queued]>
[2023-11-15T16:52:12.762+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Projet1.Extract manual__2023-11-15T16:52:10.553396+00:00 [queued]>
[2023-11-15T16:52:12.763+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-15T16:52:12.777+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Extract> on 2023-11-15 16:52:10.553396+00:00
[2023-11-15T16:52:12.782+0000] {standard_task_runner.py:57} INFO - Started process 54212 to run task
[2023-11-15T16:52:12.786+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Projet1', 'Extract', 'manual__2023-11-15T16:52:10.553396+00:00', '--job-id', '194', '--raw', '--subdir', 'DAGS_FOLDER/Projet.py', '--cfg-path', '/tmp/tmp1iikwjtp']
[2023-11-15T16:52:12.788+0000] {standard_task_runner.py:85} INFO - Job 194: Subtask Extract
[2023-11-15T16:52:12.838+0000] {task_command.py:416} INFO - Running <TaskInstance: Projet1.Extract manual__2023-11-15T16:52:10.553396+00:00 [running]> on host fb26c01043df
[2023-11-15T16:52:12.921+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Projet1' AIRFLOW_CTX_TASK_ID='Extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-15T16:52:10.553396+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-15T16:52:10.553396+00:00'
[2023-11-15T16:52:13.275+0000] {warnings.py:109} WARNING - /opt/***/dags/Projet.py:15: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_urgences = pd.read_csv(csv_file_path_urgences,  delimiter=';' )

[2023-11-15T16:52:13.595+0000] {logging_mixin.py:151} INFO - 0           1
1           1
2           1
3           1
4           1
         ... 
214216    976
214217    976
214218    976
214219    976
214220    976
Name: dep, Length: 214221, dtype: object
[2023-11-15T16:52:13.936+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Projet.py", line 30, in extract_data
    df_urgences[columns_to_convert] = df_urgences[columns_to_convert].fillna()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 5493, in fillna
    return super().fillna(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 6859, in fillna
    value, method = validate_fillna_kwargs(value, method)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/util/_validators.py", line 288, in validate_fillna_kwargs
    raise ValueError("Must specify a fill 'value' or 'method'.")
ValueError: Must specify a fill 'value' or 'method'.
[2023-11-15T16:52:13.970+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Projet1, task_id=Extract, execution_date=20231115T165210, start_date=20231115T165212, end_date=20231115T165213
[2023-11-15T16:52:13.989+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 194 for task Extract (Must specify a fill 'value' or 'method'.; 54212)
[2023-11-15T16:52:14.023+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-15T16:52:14.051+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
