[2023-11-23T15:33:41.282+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Projet1.generate_plot manual__2023-11-23T15:33:35.688253+00:00 [queued]>
[2023-11-23T15:33:41.297+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Projet1.generate_plot manual__2023-11-23T15:33:35.688253+00:00 [queued]>
[2023-11-23T15:33:41.298+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-23T15:33:41.317+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): generate_plot> on 2023-11-23 15:33:35.688253+00:00
[2023-11-23T15:33:41.323+0000] {standard_task_runner.py:57} INFO - Started process 4467 to run task
[2023-11-23T15:33:41.327+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Projet1', 'generate_plot', 'manual__2023-11-23T15:33:35.688253+00:00', '--job-id', '604', '--raw', '--subdir', 'DAGS_FOLDER/Projet.py', '--cfg-path', '/tmp/tmpq2ub5gaq']
[2023-11-23T15:33:41.329+0000] {standard_task_runner.py:85} INFO - Job 604: Subtask generate_plot
[2023-11-23T15:33:41.379+0000] {task_command.py:416} INFO - Running <TaskInstance: Projet1.generate_plot manual__2023-11-23T15:33:35.688253+00:00 [running]> on host b36ebcee5948
[2023-11-23T15:33:41.460+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Projet1' AIRFLOW_CTX_TASK_ID='generate_plot' AIRFLOW_CTX_EXECUTION_DATE='2023-11-23T15:33:35.688253+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-23T15:33:35.688253+00:00'
[2023-11-23T15:33:41.472+0000] {base.py:73} INFO - Using connection ID 'postgres_connexion' for task execution.
[2023-11-23T15:33:41.484+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/common/sql/hooks/sql.py:219: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return psql.read_sql(sql, con=conn, params=parameters, **kwargs)

[2023-11-23T15:33:43.102+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Projet.py", line 139, in generate_plot
    plt.figure(figsize=(10, 6))
NameError: name 'plt' is not defined
[2023-11-23T15:33:43.118+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Projet1, task_id=generate_plot, execution_date=20231123T153335, start_date=20231123T153341, end_date=20231123T153343
[2023-11-23T15:33:43.135+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 604 for task generate_plot (name 'plt' is not defined; 4467)
[2023-11-23T15:33:43.190+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-23T15:33:43.224+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
