[2023-11-23T19:30:50.479+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Projet1.Extract manual__2023-11-23T19:30:30.306375+00:00 [queued]>
[2023-11-23T19:30:50.494+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Projet1.Extract manual__2023-11-23T19:30:30.306375+00:00 [queued]>
[2023-11-23T19:30:50.494+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-23T19:30:50.513+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Extract> on 2023-11-23 19:30:30.306375+00:00
[2023-11-23T19:30:50.525+0000] {standard_task_runner.py:57} INFO - Started process 1066 to run task
[2023-11-23T19:30:50.528+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Projet1', 'Extract', 'manual__2023-11-23T19:30:30.306375+00:00', '--job-id', '679', '--raw', '--subdir', 'DAGS_FOLDER/Projet.py', '--cfg-path', '/tmp/tmpbxyf2eb6']
[2023-11-23T19:30:50.530+0000] {standard_task_runner.py:85} INFO - Job 679: Subtask Extract
[2023-11-23T19:30:50.598+0000] {task_command.py:416} INFO - Running <TaskInstance: Projet1.Extract manual__2023-11-23T19:30:30.306375+00:00 [running]> on host b36ebcee5948
[2023-11-23T19:30:50.699+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Projet1' AIRFLOW_CTX_TASK_ID='Extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-23T19:30:30.306375+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-23T19:30:30.306375+00:00'
[2023-11-23T19:30:51.025+0000] {warnings.py:109} WARNING - /opt/***/dags/Projet.py:31: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_urgences = pd.read_csv(csv_file_path_urgences, delimiter=';')

[2023-11-23T19:30:51.577+0000] {logging_mixin.py:151} INFO - Index(['code_age', 'agess'], dtype='object')
[2023-11-23T19:30:51.577+0000] {logging_mixin.py:151} INFO - Une erreur s'est produite lors de l'extraction des données Age : 'DataFrame' object has no attribute 'append'
[2023-11-23T19:30:51.588+0000] {base.py:73} INFO - Using connection ID 'postgres_connexion' for task execution.
[2023-11-23T19:30:51.671+0000] {logging_mixin.py:151} INFO - Une erreur s'est produite : (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "Departements_pkey"
DETAIL:  Key (num_dep)=(1) already exists.

[SQL: INSERT INTO "Departements" (num_dep, dep_name, region_name) VALUES (%(num_dep)s, %(dep_name)s, %(region_name)s)]
[parameters: ({'num_dep': 1, 'dep_name': 'Ain', 'region_name': 'Auvergne-Rhône-Alpes'}, {'num_dep': 2, 'dep_name': 'Aisne', 'region_name': 'Hauts-de-France'}, {'num_dep': 3, 'dep_name': 'Allier', 'region_name': 'Auvergne-Rhône-Alpes'}, {'num_dep': 4, 'dep_name': 'Alpes-de-Haute-Provence', 'region_name': "Provence-Alpes-Côte d'Azur"}, {'num_dep': 5, 'dep_name': 'Hautes-Alpes', 'region_name': "Provence-Alpes-Côte d'Azur"}, {'num_dep': 6, 'dep_name': 'Alpes-Maritimes', 'region_name': "Provence-Alpes-Côte d'Azur"}, {'num_dep': 7, 'dep_name': 'Ardèche', 'region_name': 'Auvergne-Rhône-Alpes'}, {'num_dep': 8, 'dep_name': 'Ardennes', 'region_name': 'Grand Est'}  ... displaying 10 of 100 total bound parameter sets ...  {'num_dep': 0, 'dep_name': 'tunisie', 'region_name': 'La Réunion'}, {'num_dep': 976, 'dep_name': 'Mayotte', 'region_name': 'Mayotte'})]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2023-11-23T19:30:52.497+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-23T19:30:52.518+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Projet1, task_id=Extract, execution_date=20231123T193030, start_date=20231123T193050, end_date=20231123T193052
[2023-11-23T19:30:52.574+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-23T19:30:52.594+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
