[2023-11-24T14:52:24.927+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Projet1.Extract manual__2023-11-24T14:52:00.943070+00:00 [queued]>
[2023-11-24T14:52:24.939+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Projet1.Extract manual__2023-11-24T14:52:00.943070+00:00 [queued]>
[2023-11-24T14:52:24.939+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-24T14:52:24.954+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Extract> on 2023-11-24 14:52:00.943070+00:00
[2023-11-24T14:52:24.962+0000] {standard_task_runner.py:57} INFO - Started process 122 to run task
[2023-11-24T14:52:24.967+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Projet1', 'Extract', 'manual__2023-11-24T14:52:00.943070+00:00', '--job-id', '908', '--raw', '--subdir', 'DAGS_FOLDER/Projet.py', '--cfg-path', '/tmp/tmpl_gs_uau']
[2023-11-24T14:52:24.968+0000] {standard_task_runner.py:85} INFO - Job 908: Subtask Extract
[2023-11-24T14:52:25.023+0000] {task_command.py:416} INFO - Running <TaskInstance: Projet1.Extract manual__2023-11-24T14:52:00.943070+00:00 [running]> on host b36ebcee5948
[2023-11-24T14:52:25.119+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Projet1' AIRFLOW_CTX_TASK_ID='Extract' AIRFLOW_CTX_EXECUTION_DATE='2023-11-24T14:52:00.943070+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-24T14:52:00.943070+00:00'
[2023-11-24T14:52:25.349+0000] {warnings.py:109} WARNING - /opt/***/dags/Projet.py:34: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_urgences = pd.read_csv(csv_file_path_urgences, delimiter=';')

[2023-11-24T14:52:25.824+0000] {logging_mixin.py:151} INFO - Index(['code_age', 'agess'], dtype='object')
[2023-11-24T14:52:25.837+0000] {base.py:73} INFO - Using connection ID 'postgres_connexion' for task execution.
[2023-11-24T14:52:25.870+0000] {logging_mixin.py:151} INFO - Une erreur s'est produite : (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "Departement_pkey"
DETAIL:  Key (num_dep)=(01) already exists.

[SQL: INSERT INTO "Departement" (num_dep, dep_name, region_name) VALUES (%(num_dep)s, %(dep_name)s, %(region_name)s)]
[parameters: ({'num_dep': '01', 'dep_name': 'Ain', 'region_name': 'Auvergne-Rhône-Alpes'}, {'num_dep': '02', 'dep_name': 'Aisne', 'region_name': 'Hauts-de-France'}, {'num_dep': '03', 'dep_name': 'Allier', 'region_name': 'Auvergne-Rhône-Alpes'}, {'num_dep': '04', 'dep_name': 'Alpes-de-Haute-Provence', 'region_name': "Provence-Alpes-Côte d'Azur"}, {'num_dep': '05', 'dep_name': 'Hautes-Alpes', 'region_name': "Provence-Alpes-Côte d'Azur"}, {'num_dep': '06', 'dep_name': 'Alpes-Maritimes', 'region_name': "Provence-Alpes-Côte d'Azur"}, {'num_dep': '07', 'dep_name': 'Ardèche', 'region_name': 'Auvergne-Rhône-Alpes'}, {'num_dep': '08', 'dep_name': 'Ardennes', 'region_name': 'Grand Est'}  ... displaying 10 of 102 total bound parameter sets ...  {'num_dep': '0', 'dep_name': 'tunisie', 'region_name': 'La Réunion'}, {'num_dep': '976', 'dep_name': 'Mayotte', 'region_name': 'Mayotte'})]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2023-11-24T14:52:25.870+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Projet.py", line 168, in extract_data
    x = tables['dep']
UnboundLocalError: local variable 'tables' referenced before assignment
[2023-11-24T14:52:25.886+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Projet1, task_id=Extract, execution_date=20231124T145200, start_date=20231124T145224, end_date=20231124T145225
[2023-11-24T14:52:25.904+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 908 for task Extract (local variable 'tables' referenced before assignment; 122)
[2023-11-24T14:52:25.944+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-24T14:52:25.963+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
